import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./globals.module.css"
import Header from "../ui/components/Header/Header"
import Footer from "../ui/components/Footer/Footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.mainBody}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
